component_depth: 8
languages:
- java
exclude:
- /node_modules/.*
- /react/.*
production:
    exclude:
      - /aws-lambda/GoDuke/src/main/java/com/goduke/validator/.*
      - /aws-lambda/GoDuke/src/main/java/com/goduke/model/.*
test:
    include:
      - /aws-lambda/GoDuke/src/main/java/com/goduke/test/.*\.java
