package com.goduke.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.goduke.converter.CandidateTypeConverter;
import com.goduke.converter.TestTypeConverter;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

@DynamoDBTable(tableName = "answers")
public class Answer implements Serializable {

    private String id;
    private Test test;
    private Candidate candidate;
    private List<String> answers;

    public Answer(){

    }

    public Answer(String id, Test test, Candidate candidate, List<String> answers) {
        this.id = id;
        this.test = test;
        this.candidate = candidate;
        this.answers = answers;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBTypeConverted(converter = TestTypeConverter.class)
    @DynamoDBAttribute(attributeName = "test")
    public Test getTest() {
        return test;
    }

    @DynamoDBAttribute(attributeName = "test")
    public void setTest(Test test) {
        this.test = test;
    }

    @DynamoDBTypeConverted(converter = CandidateTypeConverter.class)
    @DynamoDBAttribute(attributeName = "candidate")
    public Candidate getCandidate() {
        return candidate;
    }

    @DynamoDBAttribute(attributeName = "candidate")
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

    @DynamoDBAttribute(attributeName = "answers")
    public List<String> getAnswers() {
        return answers;
    }

    public void setAnswers(List<String> answers) {
        this.answers = answers;
    }
}
