package com.goduke.model;

<<<<<<< HEAD
import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "candidates")
public class Candidate implements Serializable {

	private static final long serialVersionUID = 1L;

	private String id;
	private String firstname;
	private String lastname;
	private String email;
	
	public Candidate() {}
	
	public Candidate(String id, String firstname, String lastname, String email) {
		super();
		this.id = id;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
	}

	@DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	@DynamoDBAttribute(attributeName = "firstname")
	public String getFirstname() {
		return firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}
	@DynamoDBAttribute(attributeName = "lastname")
	public String getLastname() {
		return lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}
	@DynamoDBAttribute(attributeName = "email")
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
=======
import java.nio.charset.Charset;
import java.util.Random;

import com.google.gson.Gson;

public class Candidate {
	private Integer id;
	private String username;
	private String code;
	
	public Candidate() {
		// TODO Auto-generated constructor stub
	}
	public Candidate(String json) {
		Gson gson = new Gson();
		Candidate request = gson.fromJson(json, Candidate.class);
        this.id = request.getId();
        this.username = request.getUsername();
        this.code = generateRandomCode();
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	private String generateRandomCode() {
	    byte[] array = new byte[4];
	    new Random().nextBytes(array);
	    return new String(array, Charset.forName("UTF-8"));
>>>>>>> tereszczuk
	}
	

}
