package com.goduke.model;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.goduke.converters.QuestionTypeConventer;

@DynamoDBTable(tableName = "RecruitmentTests")
public class RecruitmentTest {
	private Integer id;
	private List<String> languages;
	private String name;
	private List<Question> questions;
	private Integer recruiterid;
	private List<Integer> candidatesIds;

	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName = "languages")
	public List<String> getLanguages() {
		return languages;
	}

	public void setLanguages(List<String> languages) {
		this.languages = languages;
	}

	@DynamoDBAttribute(attributeName = "test_name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	@DynamoDBTypeConverted(converter = QuestionTypeConventer.class)
	@DynamoDBAttribute(attributeName = "questions")
	public List<Question> getQuestions() {
		return questions;
	}

	@DynamoDBAttribute(attributeName = "questions")
	public void setQuestions(List<Question> questions) {
		this.questions = questions;
	}

	@DynamoDBAttribute(attributeName = "recruiter_Id")
	public Integer getRecruiterid() {
		return recruiterid;
	}

	public void setRecruiterid(Integer recruiterid) {
		this.recruiterid = recruiterid;
	}

	@DynamoDBAttribute(attributeName = "candidates_ids")
	public List<Integer> getCandidatesIds() {
		return candidatesIds;
	}

	public void setCandidatesIds(List<Integer> candidatesIds) {
		this.candidatesIds = candidatesIds;
	}
	
	
	
}
