package com.goduke.model;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.google.gson.Gson;

@DynamoDBTable(tableName = "RecruitmentTests")
public class RecruitmentTest {
	private String id;
	private List<String> languages;
	private String name;
//	private List<Question> questions;
	private String recruiterid;
	private List<String> candidatesIds;
	
	public RecruitmentTest() {
		
	}
	
	public RecruitmentTest(String json) {
		Gson gson = new Gson();
		RecruitmentTest request = gson.fromJson(json, RecruitmentTest.class);
		this.id = request.getId();
		this.languages = request.getLanguages();
		this.name = request.getName();
//		this.questions = request.getQuestions();
		this.recruiterid = request.getRecruiterid();
		this.candidatesIds = request.getCandidatesIds();
	}

	@DynamoDBHashKey(attributeName = "Id")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName = "languages")
	public List<String> getLanguages() {
		return languages;
	}

	public void setLanguages(List<String> languages) {
		this.languages = languages;
	}

	@DynamoDBAttribute(attributeName = "test_name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
//	@DynamoDBTypeConverted(converter = QuestionTypeConventer.class)
//	@DynamoDBAttribute(attributeName = "questions")
//	public List<Question> getQuestions() {
//		return questions;
//	}
//
//	@DynamoDBAttribute(attributeName = "questions")
//	public void setQuestions(List<Question> questions) {
//		this.questions = questions;
//	}

	@DynamoDBAttribute(attributeName = "recruiter_Id")
	public String getRecruiterid() {
		return recruiterid;
	}

	public void setRecruiterid(String recruiterid) {
		this.recruiterid = recruiterid;
	}

	@DynamoDBAttribute(attributeName = "candidates_ids")
	public List<String> getCandidatesIds() {
		return candidatesIds;
	}

	public void setCandidatesIds(List<String> candidatesIds) {
		this.candidatesIds = candidatesIds;
	}
	
	public String toJson() {
		Gson gson = new Gson();
		return gson.toJson(this);
	}
}
