package com.goduke.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.goduke.converter.CandidatesTypeConverter;
import com.goduke.converter.QuestionsTypeConverter;
import com.goduke.converter.RecruiterTypeConverter;

import java.io.Serializable;
import java.util.List;

@DynamoDBTable(tableName = "tests")
public class Test implements Serializable {

	private String id;
	private List<String> languages;
	private String name;
	private List<Question> questions;
	private String recruiterId;
	private List<Candidate> candidates;

	public Test(){

	}

	public Test(String id, List<String> languages, String name, List<Question> questions, String recruiterId, List<Candidate> candidates){
		this.id = id;
		this.languages = languages;
		this.name = name;
		this.questions = questions;
		this.recruiterId = recruiterId;
		this.candidates = candidates;
	}

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId(){
		return this.id;
	}

	public void setId(String id){
		this.id = id;
	}

	@DynamoDBAttribute(attributeName = "languages")
	public List<String> getLanguages(){
		return this.languages;
	}

	public void setLanguages(List<String> languages){
		this.languages = languages;
	}

	@DynamoDBAttribute(attributeName = "name")
	public String getName(){
		return this.name;
	}

	public void setName(String name){
		this.name = name;
	}

	@DynamoDBTypeConverted(converter = QuestionsTypeConverter.class)
	@DynamoDBAttribute(attributeName = "questions")
	public List<Question> getQuestions(){
		return this.questions;
	}

	@DynamoDBAttribute(attributeName = "questions")
	public void setQuestions(List<Question> questions){
		this.questions = questions;
	}


	@DynamoDBTypeConverted(converter = RecruiterTypeConverter.class)
	@DynamoDBAttribute(attributeName = "recruiter")
	public String getRecruiterId(){
		return this.recruiterId;
	}

	@DynamoDBAttribute(attributeName = "recruiter")
	public void setRecruiterId(String recruiterId){
		this.recruiterId = recruiterId;
	}

	@DynamoDBTypeConverted(converter = CandidatesTypeConverter.class)
	@DynamoDBAttribute(attributeName = "candidates")
	public List<Candidate> getCandidates(){
		return this.candidates;
	}

	@DynamoDBAttribute(attributeName = "candidates")
	public void setCandidates(List<Candidate> candidates){
		this.candidates = candidates;
	}

}
